# Generated by Django 3.1.4 on 2021-02-08 16:20

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_category', models.CharField(max_length=200)),
                ('category_summary', models.CharField(max_length=200)),
                ('category_slug', models.CharField(default=1, max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='JobInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=100)),
                ('job_company', models.CharField(max_length=150)),
                ('job_salary', models.CharField(max_length=100)),
                ('job_location', models.CharField(max_length=100)),
                ('job_published', models.DateTimeField(default=datetime.datetime(2021, 2, 8, 21, 50, 16, 109516), verbose_name='Job published')),
                ('job_summary', models.CharField(max_length=200)),
                ('job_slug', models.CharField(default=1, max_length=200)),
                ('job_category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.jobcategory', verbose_name='Category')),
            ],
            options={
                'verbose_name_plural': 'Information',
            },
        ),
    ]
