# Generated by Django 3.1.4 on 2021-02-09 16:53

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobinformation',
            name='job_published',
            field=models.DateField(default=datetime.date.today, verbose_name='Job published'),
        ),
        migrations.CreateModel(
            name='CandidateApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('dob', models.DateField(null=True)),
                ('gender', models.CharField(choices=[('Male', 'male'), ('Female', 'female'), ('Prefer Not To Say', 'prefer not to say')], max_length=200, null=True)),
                ('contact_number', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('prev_experience', models.BooleanField()),
                ('job_company', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.jobinformation', verbose_name='Information')),
                ('job_title', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='+', to='main.jobinformation', verbose_name='Information')),
            ],
            options={
                'verbose_name_plural': 'Candidates',
            },
        ),
    ]
