# Generated by Django 3.1.4 on 2021-02-09 16:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210209_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobinformation',
            name='job_published',
            field=models.DateField(default=datetime.date(2021, 2, 9), verbose_name='Job Published'),
        ),
    ]
