# Generated by Django 3.1.4 on 2021-02-09 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210210_0153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidateapplication',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='candidateapplication',
            name='job_title',
        ),
        migrations.AddField(
            model_name='candidateapplication',
            name='date_of_birth',
            field=models.DateField(help_text='yyyy/mm/dd format', null=True),
        ),
        migrations.AddField(
            model_name='candidateapplication',
            name='job_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.jobcategory', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='candidateapplication',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('prefer not to say', 'Prefer Not To Say')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='candidateapplication',
            name='job_company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.jobinformation', verbose_name='Job Company'),
        ),
    ]
