# Generated by Django 3.1.4 on 2021-02-10 13:11

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20210210_1250'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidateapplication',
            options={'verbose_name_plural': 'CandidateApplications'},
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('bio', models.CharField(max_length=200, verbose_name='About Me: ')),
                ('opentowork', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=200, verbose_name='Open To Work')),
                ('job_category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.jobcategory', verbose_name='Interested Job Category')),
            ],
        ),
        migrations.CreateModel(
            name='AppliedJobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_posted', models.DateTimeField(default=datetime.datetime.now)),
                ('job_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applied_job', to='main.jobinformation')),
            ],
        ),
    ]
