# Generated by Django 3.1.4 on 2021-02-10 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20210210_1841'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=50)),
                ('post_description', models.CharField(max_length=250)),
                ('post_slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='jobinformation',
            name='job_slug',
            field=models.SlugField(unique=True),
        ),
    ]
