# Generated by Django 3.1.4 on 2021-02-11 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20210211_0103'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AppliedJobs',
        ),
    ]
