# Generated by Django 3.1.4 on 2021-02-11 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_delete_appliedjobs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobinformation',
            name='job_slug',
            field=models.CharField(default='FfvDvx', max_length=6, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_slug',
            field=models.CharField(default='uiiDbb', max_length=6, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.CharField(max_length=200, verbose_name='About Me'),
        ),
    ]
