# Generated by Django 3.1.4 on 2021-02-11 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20210211_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobinformation',
            name='job_slug',
            field=models.CharField(default='CvsTbI', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_slug',
            field=models.CharField(default='fcS9BN', max_length=100, unique=True),
        ),
    ]
