# Generated by Django 3.1.4 on 2021-02-12 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20210211_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobinformation',
            name='job_slug',
            field=models.CharField(default='kUPNiT', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_slug',
            field=models.CharField(default='wZbQmf', max_length=100, unique=True),
        ),
    ]
